server:
  port: 8088


spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/shiro-jwt?autoReconnect=true&useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password:
      filters: log4j,wall,mergeStat